"""alter resume2

Revision ID: 17527015388e
Revises: 5558463341b1
Create Date: 2024-11-09 16:17:29.289549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17527015388e'
down_revision: Union[str, None] = '5558463341b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume', 'file_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('file_path', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
