"""alter resume

Revision ID: 5558463341b1
Revises: 10c254f3efa0
Create Date: 2024-11-09 16:16:15.336586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5558463341b1'
down_revision: Union[str, None] = '10c254f3efa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('file_name', sa.String(length=32), nullable=False))
    op.add_column('resume', sa.Column('file_path', sa.String(length=256), nullable=False))
    op.alter_column('resume', 'name',
               existing_type=sa.VARCHAR(length=512),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.drop_column('resume', 'lastname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume', sa.Column('lastname', sa.VARCHAR(length=512), autoincrement=False, nullable=False))
    op.alter_column('resume', 'name',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=512),
               existing_nullable=False)
    op.drop_column('resume', 'file_path')
    op.drop_column('resume', 'file_name')
    # ### end Alembic commands ###
